### ISSUE TITLE
AppVeyor doesn't build the binary in WSL

### ISSUE THREAD

**Issue by wx257osn2** [poacpm/poac#114]
Currently, README says that the result of AppVeyor building is build status on WSL.
However, the result is build status using MSVC, not on WSL.
The description should be changed.

**Comment by matken11235** [comment]
Thanks, @wx257osn2 
I agree with you. But poac cannot be serve compiled binary on MSVC not yet, so it cannot be said that support Windows. I'll need a little more time to think about this...
