### ISSUE TITLE
poac has been added to the Arch User Repository

### ISSUE THREAD

**Issue by takagiy** [poacpm/poac#195]
I've added poac to the Arch User Repository(also called AUR). It is familiar to the users of arch linux and the derivative distros.
Would you check the package configuration, therefore? Especially i'm not so sure about the runtime dependencies and the build options. There are three versions of  the distribution.
- [`poac`](https://aur.archlinux.org/packages/poac/) sourcing from the GitHub releases
- [`paoc-git`](https://aur.archlinux.org/packages/poac-git/) sourcing from the master branch
- [`poac-devel-git`](https://aur.archlinux.org/packages/poac-devel-git/) sourcing from the develop branch

Configurations can be checked in “_View PKGBUILD_” on the right side of the AUR page. 
The runtime dependencies are described by the `depends` in PKGBUILD. The build time dependencies are described by the `makedepends` and the `optdepends` reperesents the packages that isn’t necessary but often useful.
The packages will be built, following the steps in `build()` in the PKGBUILD.

\- note. poac depends on the openssl, but I ommited it because git or libgit2 also depends on it.

I think it will be kindful to offer the AUR packages to arch users on README.md.
Thank you.

regarding to: #78

**Comment by ken-matsui** [comment]
Thank you for your awesome work! 
I plan to treat other package sources as 3rd party installations outside affiliated with Poac maintainers.
Therefore, please ask me the way to build Poac through issues or discussions if you kindly want to maintain the repos even though the way is continuing to be dramatically changed :)
