### ISSUE TITLE
Support dev-dependencies for development packages

### ISSUE THREAD

**Issue by ken-matsui** [poacpm/poac#53]

**Comment by supremestdoggo** [comment]
Could you please clarify what exactly this issue is?

**Comment by ken-matsui** [comment]
Hey @supremestdoggo,
Thanks for taking an interest in my project. This issue intends that Poac needs supporting dev-dependencies for development only such as testing tools and linters. Cargo implements the dev-dependency feature as well, and so many package managers do. The issue name so no sense that I will fix it.
