### ISSUE TITLE
Is the project still under active development?

### ISSUE THREAD

**Issue by qqiangwu** [poacpm/poac#683]
I find poac the most interesting package manager compared to cmake/xmake and I want to add [conan](conan.io) support for poac. Do you consider this necessary? Or you have your own plans.

**Comment by ken-matsui** [comment]
Hey @qqiangwu - thanks for reaching out. Any contributions are very welcome. Since I'm a university student, I just do not have enough time to code during a quarter; however, I can review pull requests.
