### ISSUE TITLE
ドキュメントのビルド要件が誤っている; boost

### ISSUE THREAD

**Issue by usagi** [poacpm/poac#77]
## 状況

ドキュメントでは boost-1.48 以降でビルド可能な事になっている。

- <https://docs.poac.pm/en/getting-started/installation.html>

しかし、実際にビルドを試みると Boost.Beast ライブラリーを使用しているため、 boost-1.66 以降でなければビルドできない。

## 想定される対処

- ドキュメント・バグとしてビルド要件の表記を boost-1.66 以降へ修正

### その他のオプション

- Boost.Beast を使用しないビルドモードを用意し `cmake` 引数等で設定可能にする

**Comment by matken11235** [comment]
@usagi ありがとうございます！
`docs/ja`及び`README.md`は最新の状態にしていましたが、`docs/en`の方は追いついていなかったので修正しておきます。
