### ISSUE TITLE
一般性の高いクロスプラットフォーム対応; 例えば Ubuntu の標準的なシステムパッケージ

### ISSUE THREAD

**Issue by usagi** [poacpm/poac#78]
## 状況

- 多くの一般C++erが試しやすい環境想定として ubuntu 現行版や WSL の相当環境でソースコードの改変無しにビルド可能だとユーザーも広がると思う。しかし、現時点ではおそらく OSX の特定パッケージマネージャー等による環境でのビルドしか想定されていないと思われる。

### 例として ubuntu システムパッケージによるビルド環境での具体的な問題

- `yaml-dev` システムパッケージで導入される `YAML` のヘッダーは `/usr/include/yaml.h` のように導入される。
    - 現状 `poac` ソースコードでは複数箇所で `YAML` のヘッダーの所在に独自のプリフィックス（サブ・ディレクトリー） `yaml-cpp/` を想定した `#include` が定義されているため、この部分のソースコードの改変が必要。
    - この問題への提案としては、  [yaml/libyaml の配置](https://github.com/yaml/libyaml/tree/master/include) から一般的にはサブディレクトリーなしで配置されている想定で `#include` を書き、必要に応じて `#ifdef` 等で `yaml-cpp/` を与えるのがよいのではないか、と思う。（私は OSX 開発環境に詳しくないので `__APPLE__` とすべきか、あるいは特定パッケージマネージャーを判定する方法があるか、または `cmake` レベルでヘッダーの所在を探索して変数へ入れるべきかまではわかりません。）

-----

せっかくなので遊んでみよう！と思ったのですが、イケメンC++erだけでなく、一般C++erも手軽にビルドできないとちょっと厳しいかなーと思います。あるいはバイナリーパッケージを提供してしまうというのも手だけど…。

**Comment by matken11235** [comment]
@usagi ありがとうございます。
元々ビルド済みバイナリを配布する予定でしたが、yaml-cppの件はあまり認知していませんでした。
C++17を前提としているので、`__has_include`で`yaml-cpp/yaml.h`と`yaml.h`で分岐するのが良いと思います。
どちらにせよ要求する環境が厳しいので、最終的にはビルド済みバイナリを配布します。

**Comment by wx257osn2** [comment]
@usagi `poac` が依存しているのは [LibYAML](https://github.com/yaml/libyaml) (Ubuntuのパッケージだと `libyaml-dev`)ではなく [yaml-cpp](https://github.com/jbeder/yaml-cpp) (Ubuntuのパッケージだと `libyaml-cpp-dev`)であり，ディレクトリ構造についても正しいです．  

ただ，Ubuntuだと `libyaml-cpp-dev` でyaml-cppの0.6.0以上が降ってくるのはDisco Dingo(19.04)以降みたいなので，このissueはもうしばらく(各ディストリのパッケージが出揃うまで)待ち，だと思います．

**Comment by wx257osn2** [comment]
Disco Dingoがリリースされたので試してみましたが，標準インストール環境に公式リポジトリのBoost，Cmake，OpenSSL(ライブラリの方)，yaml-cppを入れた状態でビルドできました(ご報告まで)

**Comment by matken11235** [comment]
@wx257osn2
おお！ありがとうございます！
Disco Dingoが一般的とは言えないので、このissueは残しておきます。

**Comment by wx257osn2** [comment]
まぁそうですねぇ，来年の今頃には(20.04 LTSが出たら)閉じてもいいかもしれない…？

**Comment by matken11235** [comment]
そうしましょう！

**Comment by wx257osn2** [comment]
@matken11235 というわけでFocal Fossa(Ubuntu 20.04 LTS)がリリースされたので試しました．

```shell-session
# apt install g++ libboost-dev libboost-filesystem-dev libboost-system-dev \
          libasio-dev libssl-dev cmake libyaml-cpp-dev
$ wget https://github.com/poacpm/poac/archive/0.2.1.tar.gz
$ tar zxvf 0.2.1.tar.gz
$ cd poac-0.2.1
$ mkdir build && cd $_
$ cmake ..
$ make
# make install
$ poac
```

で正しくpoacのUsageが表示されることを確認しました．

**Comment by matken11235** [comment]
@wx257osn2 
ご対応いただきありがとうございます。

@usagi 
では、このIssueは閉じさせていただきます。

お二方ともご協力ありがとうございました！
